# + -------------------------------------------------------------------------------- + #
# | BOT SETTINGS ( 봇 설정 )
# |
# | 임베드 사용법 (예시)
# |  Embed:
# |    title: ""
# |    content: ""
# |    footer: ""
# |    color: "0x00CCFF"
# + -------------------------------------------------------------------------------- + #
bot:
  # 실행 될 봇 토큰 (TOKEN) - 필수로 입력하세요!
  token: #

  # 봇 상태 설정 [ ONLINE (온라인), IDLE (자리비움), DND (다른 용무중) ]
  status: ONLINE

  # 디스코트 채팅 마인크래프트로 연동
  # {user} 로 닉네임 불러오기
  discordMessage: ">> <{user}> {message}"

  # 웹훅 URL - 필수로 입력하세요!
  webhook:
    url: #
    avatarUrl: "https://mc-heads.net/head/"

  # 서버 열릴때
  onServer:
    channelId: "000000000000000000"
    # 알림 메시지
    content: #
    # 알림 임베드
    Embed:
      title:  #
      content: #
      footer: #
      color: #

  # 서버 닫힐 때
  offServer:
    # 알림을 보낼 채널
    channelId: "000000000000000000"
    # 알림 메시지
    content: #
    # 알림 임베드
    Embed:
      title: #
      content: #
      footer: #
      color: #

  channel:
    # 마인크래프트와 연동할 채팅 채널 ID
    chat: "000000000000000000"

  # 봇 활동 설정
  presence:

    # 봇 활동 상태 설정 (Type) [ PLAYING (~하는중), STREAMING (~방송중), LISTENING (~듣는중), WATCHING (~보는중), COMPETING (~참여중) ]
    type: PLAYING

    # 봇 활동 메시지 설정
    text: "Minecraft"

# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &6s디스코드 채팅 | &r'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

errorMessages:
  # 권한이 없을 때 출력되는 메시지
  notAnOperator: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 콘솔에서 사용이 불가능한 명령어를 사용하려고 하였을 때 출력되는 메시지
  noConsoleCommand: '&c콘솔에서는 사용이 불가능한 명령어입니다.'

  # 콘솔에서 불가능 명령어를 사용하였을 때 출력되는 메시지
  noConsoleMessage: '&c콘솔에서는 불가능한 명령어입니다. (인게임에서 시도해주세요)'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'