name: ST-DiscordChat
main: net.starly.discordchat.DiscordChat
author: Starly Team
website: http://starly.kr/

description: DiscordChat Plugin.

depend: [ ST-Core ]

version: 1.0
api-version: 1.13

commands: